### ISSUE TITLE
mdl

### ISSUE THREAD

**Issue by gedw99** [mgoulao/fuchsia-web-demo#4]
are you going to change from MDL lite to the new supported MDC ?

https://github.com/material-components/material-components-web

Cool demo. But i am guessing google will provide a Dart / Angular based supported system int he end maybe. no one knows yet.

Or they will simply use the opengl Web canvas and wasm the DART onto it

**Comment by mgoulao** [comment]
Maybe in the future, for now I think MDL lite is good enough.

**Comment by mgoulao** [comment]
Update: I have changed to MDC

**Comment by gedw99** [comment]
@mgoulao ok.. time to kick the tires !!
